name: Create Chapter

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title'
        required: true
        type: string
      index:
        description: 'Index (optional, position)'
        required: false
        type: string

jobs:
   create-chapter:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
           with:
            ref: main
         - uses: denoland/setup-deno@v1
           with:
            deno-version: latest

         - name: Get last index
           id: last-index
           run: |
            echo "Input index: '${{ github.event.inputs.index }}'"
            echo "Is empty check: $([ -z '${{ github.event.inputs.index }}' ] && echo 'true' || echo 'false')"
            
            if [ -z "${{ github.event.inputs.index }}" ]; then
              echo "No index provided, calculating next available index..."
              last_index=$(( $(ls *.md | grep -v 'README.md' | wc -l) + 1 ))
              index=$last_index
              echo "Calculated index: $index"
            else
              index=$(echo "${{ github.event.inputs.index }}" | sed 's/^0*//' | awk '{print $1+0}')
              echo "Using provided index: $index"
            fi
            echo "index=$index" >> "$GITHUB_OUTPUT"
            echo "Final Index: $index"

         - name: Create chapter
           run: |
            deno run -A ./scripts/create-chapter.ts "${{ github.event.inputs.title }}" "${{ steps.last-index.outputs.index }}"
         - name: Commit changes
           run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Move chapter ${{ github.event.inputs.title }} to index ${{ github.event.inputs.index }}"
            git push
