name: Deploy DATEX Spec

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy Spec
    runs-on: [self-hosted, unyt-main]
    
    steps:
      - name: Checkout datex-specification
        uses: actions/checkout@v4
        with: 
          path: datex-specification
					      
      - name: Checkout spec-generator
        uses: actions/checkout@v4
        with:
          repository: unyt-org/spec-generator
          path: spec-generator
          token: ${{ secrets.GITHUB_TOKEN }}
		
      - name: Check structure
        run: |
          ls -la
          ls -la spec-generator
          ls -la datex-specification	
